name: Arch Linux Build

on:
  pull_request:
  schedule:
    - cron:  '30 7 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    name: Build on Arch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cargo-C Toolchain Cache
      id: linux-cargo-c-toolchain
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: linux-cargo-c-toolchain

    - name: Setup Cargo-C Toolchain
      if: steps.linux-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c

    - name: Build HandBrake Arch Linux
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1

    - name: Upload HandBrake-SVT-AV1-PSY Archive
      uses: actions/upload-artifact@v4
      with:
        name: HandBrakePKG
        path: ${{ steps.makepkg.outputs.pkgfile0 }}


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
       
    - name: Download Artifacts - PKG Arch Linux
      uses: actions/download-artifact@v4
      with:
        name: HandBrakePKG
        path: arch/

    # Generate Hashes
    - name: Generate SHA265 Hashes
      run: |
        cd arch
        sha256sum * > sha256.txt
        cp sha256.txt ../.github/workflows/
        cd ..
        cd .github/workflows/
        sed -e 's/  / | /' -i sha256.txt
        sed -e 's/^/| /'  -i sha256.txt
        sed -e 's/$/ |/' -i sha256.txt
        cat sha256.txt >> arch_rel_body.md
      
    # Publishing the Release
    - name: Remove the old Release
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 0
        delete_tag_pattern: "arch"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "arch/*"
        name: "Snapshots for Arch Linux"
        bodyFile: .github/workflows/arch_rel_body.md
        prerelease: true
        replacesArtifacts: false
        allowUpdates: false
        tag: arch
        token: ${{ secrets.GITHUB_TOKEN }}
